// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fake-trade.proto

package com.freesia.metatradepublisher.rpc.proto;

public final class FakeTradeProto {
  private FakeTradeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_FakeTradeMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_FakeTradeMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rpc_SubmitResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rpc_SubmitResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020fake-trade.proto\022\003rpc\"\246\001\n\020FakeTradeMes" +
      "sage\022\025\n\rsenderAddress\030\001 \001(\t\022\027\n\017receiverA" +
      "ddress\030\002 \001(\t\022\016\n\006amount\030\003 \001(\001\022\021\n\ttimestam" +
      "p\030\004 \001(\003\022\021\n\tsignature\030\005 \001(\t\022\027\n\017senderPubl" +
      "icKey\030\006 \001(\t\022\023\n\013description\030\007 \001(\t\"\036\n\014Subm" +
      "itResult\022\016\n\006result\030\001 \001(\0102J\n\tFakeTrade\022=\n" +
      "\017SubmitFakeTrade\022\025.rpc.FakeTradeMessage\032" +
      "\021.rpc.SubmitResult\"\000B4\n com.freesia.meta" +
      "tradegateway.rpcB\016FakeTradeProtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rpc_FakeTradeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rpc_FakeTradeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_FakeTradeMessage_descriptor,
        new java.lang.String[] { "SenderAddress", "ReceiverAddress", "Amount", "Timestamp", "Signature", "SenderPublicKey", "Description", });
    internal_static_rpc_SubmitResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rpc_SubmitResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rpc_SubmitResult_descriptor,
        new java.lang.String[] { "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
