// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fake-trade.proto

package com.freesia.metatradegateway.rpc.proto;

public interface SubmitResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rpc.SubmitResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool result = 1;</code>
   * @return The result.
   */
  boolean getResult();
}
